name: Build and push docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Spring app
        run: ./gradlew bootjar

      - name: Login into docker registry
        uses: docker/login-action@v2.1.0
        with:
          username: 1grzyb1
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker for backend
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: 1grzyb1/aoc-slack:latest
